calvarle/user-manager-1.0.0/user-manager-webapp-primefaces/src/main/java/cl/gechs/cursojava/beans/notifications/EmailNotificationController.java
package cl.gechs.cursojava.beans.notifications;

import cl.gechs.cursojava.enums.EmailNotificationType;
import cl.gechs.cursojava.model.EmailNotification;
import cl.gechs.cursojava.beans.LoginBean;
import cl.gechs.cursojava.beans.UtilsBean;
import java.io.Serializable;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import org.primefaces.model.LazyDataModel;

/**
 *
 * @author Carlos Soza <carlos.soza at gmail.com>
 */
@ManagedBean(name = "emailNotificationController")
@SessionScoped
public class EmailNotificationController implements Serializable {

    private static final long serialVersionUID = 4357704426773030376L;
    // BEANS
    @ManagedProperty("#{utilsBean}")
    private UtilsBean utilsBean;
    @ManagedProperty("#{loginBean}")
    private LoginBean loginBean;
    // FILTERS
    private String organizationId;
    private EmailNotificationType emailNotificationType;
    // DATA
    private LazyDataModel<EmailNotification> emailNotifications;
    private EmailNotification emailNotification;

    @PostConstruct
    public void init() {
        this.emailNotifications = new EmailNotificationModel(this);
    }

    public void resetFilters() {
        this.organizationId = null;
        this.emailNotificationType = null;
    }

    public String getOrganizationId() {
        return organizationId;
    }

    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId;
    }

    public EmailNotificationType getEmailNotificationType() {
        return emailNotificationType;
    }

    public void setEmailNotificationType(EmailNotificationType emailNotificationType) {
        this.emailNotificationType = emailNotificationType;
    }

    public LazyDataModel<EmailNotification> getEmailNotifications() {
        return emailNotifications;
    }

    public void setEmailNotifications(LazyDataModel<EmailNotification> emailNotifications) {
        this.emailNotifications = emailNotifications;
    }

    public EmailNotification getEmailNotification() {
        return emailNotification;
    }

    public void setEmailNotification(EmailNotification emailNotification) {
        this.emailNotification = emailNotification;
    }

    public UtilsBean getUtilsBean() {
        return utilsBean;
    }

    public void setUtilsBean(UtilsBean utilsBean) {
        this.utilsBean = utilsBean;
    }

    public LoginBean getLoginBean() {
        return loginBean;
    }

    public void setLoginBean(LoginBean loginBean) {
        this.loginBean = loginBean;
    }

    public EmailNotificationType[] getEmailNotificationTypes() {
        return EmailNotificationType.values();
    }
}

calvarle/user-manager-1.0.0/user-manager-webapp-primefaces/src/main/java/cl/gechs/cursojava/beans/notifications/EmailNotificationModel.java
package cl.gechs.cursojava.beans.notifications;

import cl.gechs.cursojava.model.EmailNotification;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import org.primefaces.model.LazyDataModel;
import org.primefaces.model.SortOrder;

/**
 *
 * @author Carlos Soza <carlos.soza at gmail.com>
 */
public class EmailNotificationModel extends LazyDataModel<EmailNotification> {

    private static final long serialVersionUID = 6202606942101363422L;
    private final transient EmailNotificationController controller;

    public EmailNotificationModel(EmailNotificationController controller) {
        this.controller = controller;
    }

    @Override
    public EmailNotification getRowData(String rowKey) {
        return this.controller.getUtilsBean().getEmailNotificationService().getEmailNotification(rowKey);
    }

    @Override
    public Object getRowKey(EmailNotification emailNotification) {
        return emailNotification.getEmailNotificationId();
    }

    @Override
    public List<EmailNotification> load(int first, int pageSize, String sortField, SortOrder sortOrder, Map<String, Object> filters) {

        List<EmailNotification> data = new ArrayList<>();
        List<EmailNotification> emailNotifications = this.controller.getUtilsBean().getEmailNotificationService().getEmailNotifications();
        if (emailNotifications != null) {
            data.addAll(emailNotifications);
        }
        //rowCount
        int dataSize = data.size();
        this.setRowCount(dataSize);
        return data;
    }
}

calvarle/user-manager-1.0.0/user-manager-webapp-primefaces/src/main/java/cl/gechs/cursojava/beans/notifications/EmailNotificationView.java
package cl.gechs.cursojava.beans.notifications;

import cl.gechs.cursojava.commons.MailAttachment;
import cl.gechs.cursojava.commons.MailSender;
import cl.gechs.cursojava.commons.MailSenderConfig;
import cl.gechs.cursojava.commons.MailSenderFactory;
import cl.gechs.cursojava.enums.EmailNotificationType;
import cl.gechs.cursojava.model.EmailNotification;
import cl.gechs.cursojava.model.EmailNotificationDocument;
import cl.gechs.cursojava.beans.LoginBean;
import cl.gechs.cursojava.beans.UtilsBean;
import cl.gechs.cursojava.commons.Attachment;
import cl.gechs.cursojava.commons.BaseController;
import cl.gechs.cursojava.commons.RandomUtils;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.io.Serializable;
import java.nio.file.CopyOption;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import org.apache.commons.io.FilenameUtils;
import org.apache.log4j.Logger;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.primefaces.model.UploadedFile;

/**
 *
 * @author Carlos Soza C <carlos.soza at gmail.com>
 */
@ManagedBean(name = "emailNotificationView")
@ViewScoped
public class EmailNotificationView extends BaseController implements Serializable {

    private static final long serialVersionUID = -6669990565378644861L;
    private static final Logger LOGGER = Logger.getLogger(EmailNotificationView.class);
    private static final String FACTORY_EMAIL = "factory@gmail.com";
    private static final Integer FILE_NAME_RANDOM_SIZE = 10;
    private static final String TEMP_DIR = "/tmp";
    private static final String NOTIFICATIONS_DIR;
    protected static final String HTML_EDITOR_TOOLBAR = "[['Source','Preview','Print'],['Cut','Copy','Paste','PasteText','PasteFromWord','Undo','Redo'],"
            + "['Find','Replace','SelectAll'],['Bold','Italic','Underline','Strike','Subscript','Superscript','RemoveFormat']"
            + ",['Outdent','Indent','Blockquote','CreateDiv','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','BidiLtr','BidiRtl','NumberedList','BulletedList']"
            + ",['Link','Unlink','Anchor'],['Table','HorizontalRule','Smiley','SpecialChar','PageBreak','Iframe','InsertPre']"
            + ",['Styles','Format','Font','FontSize'],['TextColor','BGColor'],['UIColor','Maximize','ShowBlocks'],['About']]";

    static {
        NOTIFICATIONS_DIR = System.getProperty("jboss.home.dir") + "/standalone/resources/notifications";
    }

    // BEANS
    @ManagedProperty("#{utilsBean}")
    private UtilsBean utilsBean;
    @ManagedProperty("#{loginBean}")
    private LoginBean loginBean;
    //DATA
    private EmailNotification emailNotification;
    private EmailNotification selectedEmailNotification;
    private List<EmailNotificationDocument> selectedEmailNotificationDocuments;
    private transient List<EmailNotificationDocument> addEmailNotificationDocuments;
    private transient List<EmailNotificationDocument> emailNotificationDocuments;
    private List<String> fileNames;
    private transient StreamedContent file;

    @PostConstruct
    public void init() {
        this.initEmailNotification();
        this.addEmailNotificationDocuments = new ArrayList<>();
        this.emailNotificationDocuments = new ArrayList<>();
        this.fileNames = new ArrayList<>();
    }

    public void reinitDocument() {
        this.fileNames = new ArrayList<>();
        this.addEmailNotificationDocuments = new ArrayList<>();
    }

    public void initEmailNotification() {
        this.emailNotification = new EmailNotification();
        this.emailNotification.setOriginEmailAddress(FACTORY_EMAIL);
    }

    public void reinit() {
        this.initEmailNotification();
        this.addEmailNotificationDocuments = new ArrayList<>();
        this.emailNotificationDocuments = new ArrayList<>();
        this.fileNames = new ArrayList<>();
    }

    public EmailNotification getEmailNotification() {
        return emailNotification;
    }

    public void setEmailNotification(EmailNotification emailNotification) {
        this.emailNotification = emailNotification;
    }

    public List<EmailNotificationDocument> getEmailNotificationDocuments() {
        return emailNotificationDocuments;
    }

    public void setEmailNotificationDocuments(List<EmailNotificationDocument> emailNotificationDocuments) {
        this.emailNotificationDocuments = emailNotificationDocuments;
    }

    public List<EmailNotificationDocument> getAddEmailNotificationDocuments() {
        return addEmailNotificationDocuments;
    }

    public void setAddEmailNotificationDocuments(List<EmailNotificationDocument> addEmailNotificationDocuments) {
        this.addEmailNotificationDocuments = addEmailNotificationDocuments;
    }

    public EmailNotification getSelectedEmailNotification() {
        return selectedEmailNotification;
    }

    public void setSelectedEmailNotification(EmailNotification selectedEmailNotification) {
        this.selectedEmailNotification = selectedEmailNotification;
        List<EmailNotificationDocument> eNDocuments = this.getUtilsBean().getEmailNotificationService().getEmailNotificationDocuments(selectedEmailNotification.getEmailNotificationId());
        if (eNDocuments != null) {
            this.setSelectedEmailNotificationDocuments(eNDocuments);
        }
    }

    public List<EmailNotificationDocument> getSelectedEmailNotificationDocuments() {
        return selectedEmailNotificationDocuments;
    }

    public void setSelectedEmailNotificationDocuments(List<EmailNotificationDocument> selectedEmailNotificationDocuments) {
        this.selectedEmailNotificationDocuments = selectedEmailNotificationDocuments;
    }

    public List<String> getFileNames() {
        return fileNames;
    }

    public void setFileNames(List<String> fileNames) {
        this.fileNames = fileNames;
    }

    public UtilsBean getUtilsBean() {
        return this.utilsBean;
    }

    public LoginBean getLoginBean() {
        return this.loginBean;
    }

    public void setUtilsBean(UtilsBean utilsBean) {
        this.utilsBean = utilsBean;
    }

    public void setLoginBean(LoginBean loginBean) {
        this.loginBean = loginBean;
    }

    public void doDelete(EmailNotification emailNotification) {
        LOGGER.info("Deleting Notification: " + emailNotification.getEmailNotificationId());
        if (this.getUtilsBean().getEmailNotificationService().deleteEmailNotification(emailNotification, this.loginBean.getUsername())) {
            this.generateMainInfoMessage("Delete", " Notificacion Borrada con Èxito");
        } else {
            this.generateMainErrorMessage("Error", " Error al eliminar Notificacion");
        }
    }

    public boolean sendNotification(EmailNotification emailNotification) {
        try {
            LOGGER.info("Send Notification: " + emailNotification.getEmailNotificationId());
            List<EmailNotificationDocument> emNDocuments = this.getUtilsBean().getEmailNotificationService().getEmailNotificationDocuments(emailNotification.getEmailNotificationId());
            List<String> attachments = new ArrayList<>();
            if (emNDocuments != null && !emNDocuments.isEmpty()) {
                for (EmailNotificationDocument matt : emNDocuments) {
                    File f = new File(matt.getFilePath());
                    if (f.exists()) {
                        String ndFilename = TEMP_DIR + "/" + matt.getDocumentName();
                        LOGGER.info("Moving File\nFROM=" + matt.getFilePath() + "\nTO=" + ndFilename);
                        CopyOption[] options = new CopyOption[]{StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.COPY_ATTRIBUTES};
                        Files.copy(Paths.get(matt.getFilePath()), Paths.get(ndFilename), options);
                        attachments.add(ndFilename);
                    }
                }
            }
            this.sendEmail(emailNotification.getDestinationEmailAddress().split(","), emailNotification.getEmailSubject(), emailNotification.getEmailContent(), attachments.toArray(new String[attachments.size()]), emailNotification.getType(), emailNotification.getMailServerType());
            this.generateMainInfoMessage("OK", "Notificacion Enviada con Éxito");
        } catch (Exception ex) {
            LOGGER.error("Cannot send notifiation: " + ex.getMessage(), ex);
            this.generateMainErrorMessage("Error", " Error al enviar notificacion");
        }
        return true;
    }

    public void doSaveAndSend() {
        LOGGER.info("Send and Save Notification");
        this.doSave();
        this.sendNotification(emailNotification);
    }

    public void doSave() {
        LOGGER.info("Saving Notification");
        try {
            for (EmailNotificationDocument matt : emailNotificationDocuments) {
                // move file to the right folder
                String fileExtension = this.getFileExtension(new File(matt.getFilePath()));
                fileExtension += "." + fileExtension;
                String ndFilename = NOTIFICATIONS_DIR + "/" + RandomUtils.generateRandomID(FILE_NAME_RANDOM_SIZE).toUpperCase() + fileExtension;
                LOGGER.info("Moving File\nFROM=" + matt.getFilePath() + "\nTO=" + ndFilename);
                CopyOption[] options = new CopyOption[]{StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.COPY_ATTRIBUTES};

calvarle/user-manager-1.0.0/user-manager-webapp-primefaces/src/main/webapp/pages/notifications/dialogs/add_documents.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <!-- CREATE NOTIFICATION -->
    <p:dialog header="Agregar Documentos" widgetVar="emailNotificationDocumentsDialog" width="1200" appendTo="@(body)" modal="true" 
              showEffect="fade" hideEffect="fade" resizable="false" position="top">
        <h:form id="mailAttachmentsForm">
            <h:panelGrid columns="6" cellpadding="1" style="width: 100%">
                <h:outputLabel value="Seleccione Archivo:" for="txt_location"/>
                <p:fileUpload id="txt_location" fileUploadListener="#{emailNotificationView.handleFileUpload}" auto="true" fileLimit="5" update="txt_files_location" multiple="true"/>

                <h:outputLabel value=""/>
                <p:dataList id="txt_files_location" value="#{emailNotificationView.fileNames}" var="file" type="ordered">
                    #{file}
                </p:dataList>
                <h:outputLabel value=""/>
                <p:commandButton id="btn_add" value="Agregar" update=":mailAttachmentsForm:mailAttachmentsPanel @parent"  action="#{emailNotificationView.reinitDocument}" 
                                 actionListener="#{emailNotificationView.onAddDocument}">
                </p:commandButton>
            </h:panelGrid>

            <br></br>

            <p:outputPanel id="mailAttachmentsPanel">
                <p:dataTable value="#{emailNotificationView.emailNotificationDocuments}" var="attachmentFile"  id="documentsTable">
                    <f:facet name="header">
                        <h:outputText value="Attachments" />
                    </f:facet>
                    <p:column headerText="Nombre Documento">
                        <h:outputText value="#{attachmentFile.documentName}" />
                    </p:column>
                    <p:column headerText="Acciones" style="text-align: center" rendered="#{loginBean.isUserInRoles('ADMINISTRADOR')}">
                        <p:commandLink styleClass="ui-icon ui-icon-trash" style="display: inline-flex" update=":mailAttachmentsForm:mailAttachmentsPanel" process=":mailAttachmentsForm:mailAttachmentsPanel">
                            <p:collector value="#{attachmentFile}" removeFrom="#{emailNotificationView.emailNotificationDocuments}" unique="true"/>
                        </p:commandLink>
                        <p:commandLink  ajax="false" styleClass="ui-icon ui-icon-arrowthickstop-1-s" style="display: inline-flex" title="Descargar"
                                        onclick="PrimeFaces.monitorDownload(startDownload, stopDownload);"
                                        actionListener="#{emailNotificationView.prepareFile(attachmentFile.filePath,attachmentFile.documentName)}">
                            <p:fileDownload value="#{emailNotificationView.file}" />
                        </p:commandLink>
                    </p:column>
                </p:dataTable>
            </p:outputPanel>
        </h:form>
        <br></br>
        <hr></hr>
        <br></br>            
        <br></br>
        <h:form id="emailNotificationForm">
            <div style="float: right">
                <p:commandButton id="btn_save" value="Guardar" rendered="#{loginBean.isUserInRoles('ADMINISTRADOR')}"
                                 oncomplete="handleSubmitRequest(xhr, status, args,'emailNotificationDocumentsDialog')" update=":emailNotificationInfoForm" >
                </p:commandButton>
                &#160;&#160;&#160;&#160;
                <p:commandButton id="btn_close" value="Cerrar" onclick="PF('emailNotificationDocumentsDialog').hide()"/>
            </div>
        </h:form>
        <br/>
    </p:dialog>
</html>

calvarle/user-manager-1.0.0/user-manager-webapp-primefaces/src/main/webapp/pages/notifications/dialogs/create.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:pe="http://primefaces.org/ui/extensions">

    <!-- CREATE NOTIFICATION -->
    <p:dialog header="Nueva Notificación" widgetVar="emailNotificationDialog" width="1200" appendTo="@(body)" modal="true" 
              showEffect="fade" hideEffect="fade" resizable="false" position="top">
        <h:form id="emailNotificationInfoForm">
            <p:outputPanel id="emailNotificationPanel">
                <p:messages id="messages" showDetail="true" closable="true" autoUpdate="true"/>
                <p:panel header="Detalle" style="margin: 0px auto; margin-bottom: 20px; width: 100%" rendered="#{loginBean.isUserInRoles('ADMINISTRADOR')}">
                    <p:panelGrid style="width: 100%" class="panelgrid-noborder">
                        <p:row>
                            <p:column style="vertical-align: top;">
                                <p:outputLabel value="Tipo de Notificación:" for="txt_type" style="vertical-align: top;"/>                                
                            </p:column>
                            <p:column>
                                <p:selectOneMenu id="txt_type"  value="#{emailNotificationView.emailNotification.type}" required="true">
                                    <f:selectItem itemLabel="Seleccione" itemValue="#{null}" />
                                    <f:selectItems value="#{emailNotificationController.emailNotificationTypes}" var="type" itemValue="#{type}" itemLabel="#{type}"/>
                                </p:selectOneMenu>
                            </p:column>
                        </p:row>
                        <p:row>
                            <p:column style="vertical-align: top;">
                                <p:outputLabel value="Tipo de Servidor:" for="txt_mail_server_type" style="vertical-align: top;"/>                                
                            </p:column>
                            <p:column>
                                <p:selectOneMenu id="txt_mail_server_type"  value="#{emailNotificationView.emailNotification.mailServerType}" required="true">
                                    <f:selectItem itemLabel="Seleccione" itemValue="#{null}" />
                                    <f:selectItems value="#{emailNotificationView.mailServerTypes}" var="mailServerType" itemValue="#{mailServerType}" itemLabel="#{mailServerType}"/>
                                </p:selectOneMenu>
                            </p:column>
                        </p:row>
                        <p:row>
                            <p:column style="vertical-align: top;">        
                                <p:outputLabel value="Dirección Origen:" for="txt_from"/>                                
                            </p:column>
                            <p:column>       
                                <p:inputText id="txt_from" value="#{emailNotificationView.emailNotification.originEmailAddress}"  style="width: 100%;" readonly="true"/>
                            </p:column>
                        </p:row>
                        <p:row>
                            <p:column style="vertical-align: top;">        
                                <p:outputLabel value="Destinatarios:" for="txt_to"/>
                            </p:column>
                            <p:column>     
                                <p:inputTextarea id="txt_to" value="#{emailNotificationView.emailNotification.destinationEmailAddress}" required="true" style="width: 100%; height: 60px" readonly="false"/>
                            </p:column>
                        </p:row>
                        <p:row>
                            <p:column style="vertical-align: top;">        
                                <p:outputLabel value="Asunto:" for="txt_subject"/>
                            </p:column>
                            <p:column>           
                                <p:inputText id="txt_subject" value="#{emailNotificationView.emailNotification.emailSubject}" required="true" style="width: 100%"/>
                            </p:column>
                        </p:row>
                        <p:row>
                            <p:column  style="vertical-align: top;">        
                                <p:outputLabel value="Contenido:" for="txt_body"/>
                            </p:column>
                            <p:column>        
                                <pe:ckEditor id="txt_body" widgetVar="editorWidget" value="#{emailNotificationView.emailNotification.emailContent}" width="100%" height="400px"
                                             toolbar="#{emailNotificationView.toolbarConfig}"/>
                            </p:column>
                        </p:row>
                    </p:panelGrid>
                </p:panel>
                <br></br>
                <hr></hr>
                <p:toolbar>
                    <f:facet name="right">
                        <p:commandButton value="Editar" actionListener="#{emailNotificationView.reinitDocument()}" 
                                         rendered="#{loginBean.isUserInRoles('ADMINISTRADOR')}"
                                         update=":mailAttachmentsForm"
                                         oncomplete="PF('emailNotificationDocumentsDialog').show()" icon="fa fa-plus" title="Agregar Documents"/>
                    </f:facet>
                </p:toolbar>
                <p:dataTable value="#{emailNotificationView.emailNotificationDocuments}" var="attachmentFile"  id="documentsTable">
                    <f:facet name="header">
                        <h:outputText value="Attachments" />
                    </f:facet>
                    <p:column headerText="Nombre Documento">
                        <h:outputText value="#{attachmentFile.documentName}" />
                    </p:column>
                </p:dataTable>
            </p:outputPanel>
            <br></br>
            <hr></hr>
            <br></br>            
            <br></br>
            <div style="float: right">
                <p:commandButton id="btn_send_and_save" value="Enviar y Guardar" rendered="#{loginBean.isUserInRoles('ADMINISTRADOR')}"
                                 oncomplete="handleSubmitRequest(xhr, status, args,'emailNotificationDialog')"  action="#{emailNotificationView.doSaveAndSend()}"
                                 update=":emailNotificationsForm:emailNotificationsTable" onsuccess="PF('editorWidget').destroy()">
                </p:commandButton>
                &#160;&#160;
                <p:commandButton id="btn_save" value="Guardar" rendered="#{loginBean.isUserInRoles('ADMINISTRADOR')}"
                                 oncomplete="handleSubmitRequest(xhr, status, args,'emailNotificationDialog')"  action="#{emailNotificationView.doSave()}"
                                 update=":emailNotificationsForm:emailNotificationsTable" onsuccess="PF('editorWidget').destroy()">
                </p:commandButton>
                &#160;&#160;
                <p:commandButton id="btn_close" value="Cerrar" onclick="PF('emailNotificationDialog').hide()" onsuccess="PF('editorWidget').destroy()"/>
            </div>
        </h:form>
        <br/>
    </p:dialog>
</html>

calvarle/user-manager-1.0.0/user-manager-webapp-primefaces/src/main/webapp/pages/notifications/dialogs/view.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <!-- CREATE NOTIFICATION -->
    <p:dialog header="Detalle Notificación" widgetVar="emailNotificationDetailDialog" width="1200" appendTo="@(body)" modal="true" 
              showEffect="fade" hideEffect="fade" resizable="false" position="top">
        <h:form id="emailNotificationDetailInfoForm">
            <p:outputPanel id="emailNotificationDetailPanel">
                <p:messages id="messages" showDetail="true" closable="true" autoUpdate="true"/>
                <p:panel header="Detalle de Notificación" style="margin: 0px auto; margin-bottom: 20px; width: 100%" rendered="#{loginBean.isUserInRoles('ADMINISTRADOR')}">
                    <p:panelGrid style="width: 100%" class="panelgrid-noborder">
                        <p:row>
                            <p:column style="vertical-align: top;">
                                <p:outputLabel value="Tipo de Notificación:"/>
                            </p:column>
                            <p:column>
                                <h:outputText value="#{emailNotificationView.selectedEmailNotification.type}"/>
                            </p:column>
                        </p:row>
                        <p:row>
                            <p:column style="vertical-align: top;">
                                <p:outputLabel value="Tipo de Servidor:"/>
                            </p:column>
                            <p:column>
                                <h:outputText value="#{emailNotificationView.selectedEmailNotification.mailServerType}"/>
                            </p:column>
                        </p:row>
                        <p:row>
                            <p:column style="vertical-align: top;">
                                <p:outputLabel value="Email de Origen:"/>
                            </p:column>
                            <p:column>
                                <h:outputText value="#{emailNotificationView.selectedEmailNotification.originEmailAddress}"/>
                            </p:column>
                        </p:row>
                        <p:row>
                            <p:column style="vertical-align: top;">
                                <p:outputLabel value="Email Destinatario:"/>
                            </p:column>
                            <p:column>
                                <h:outputText value="#{emailNotificationView.selectedEmailNotification.destinationEmailAddress}"/>
                            </p:column>
                        </p:row>
                        <p:row>
                            <p:column style="vertical-align: top;">
                                <p:outputLabel value="Asunto:"/>
                            </p:column>
                            <p:column>
                                <h:outputText value="#{emailNotificationView.selectedEmailNotification.emailSubject}"/>
                            </p:column>
                        </p:row>
                        <p:row>
                            <p:column style="vertical-align: top;">
                                <p:outputLabel value="Contenido:"/>
                            </p:column>
                            <p:column>
                                <p:scrollPanel mode="native" style="height:300px">
                                    <h:outputText value="#{emailNotificationView.selectedEmailNotification.emailContent}" escape="false" style="width: 100%; height: 300px"/>
                                </p:scrollPanel>
                            </p:column>
                        </p:row>
                    </p:panelGrid>
                </p:panel>
                <br></br>
                <hr></hr>
                <p:dataTable value="#{emailNotificationView.selectedEmailNotificationDocuments}" var="attachmentFile"  id="documentsTable">
                    <f:facet name="header">
                        <h:outputText value="Attachments" />
                    </f:facet>
                    <p:column headerText="Nombre Documento">
                        <h:outputText value="#{attachmentFile.documentName}" />
                    </p:column>
                </p:dataTable>
            </p:outputPanel>
            <br></br>
            <hr></hr>
            <br></br>            
            <br></br>
            <div style="float: right">
                <p:commandButton id="btn_send" value="Re-Enviar" rendered="#{loginBean.isUserInRoles('ADMINISTRADOR')}"
                                 oncomplete="handleSubmitRequest(xhr, status, args,'emailNotificationDetailDialog')"  action="#{emailNotificationView.sendNotification(emailNotificationView.selectedEmailNotification)}"
                                 update=":emailNotificationsForm:emailNotificationsTable">
                </p:commandButton>
                &#160;&#160;
                <p:commandButton id="btn_close" value="Cerrar" onclick="PF('emailNotificationDetailDialog').hide()"/>
            </div>
        </h:form>
        <br/>
    </p:dialog>
</html>