alex_rogget_erices/user-manager-1.0.0/user-manager-webapp-primefaces/src/main/java/cl/gechs/cursojava/beans/LoginBean.java
package cl.gechs.cursojava.beans;

import cl.gechs.cursojava.model.User;
import cl.gechs.cursojava.model.UserRoleEnum;
import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import org.apache.commons.lang3.StringUtils;
import org.apache.log4j.Logger;

/**
 *
 * @author Carlos Soza <carlos.soza at gmail.com>
 */
@ManagedBean(name = "loginBean")
@SessionScoped
public class LoginBean implements Serializable {

    private static final Logger LOGGER = Logger.getLogger(LoginBean.class);
    private static final long serialVersionUID = 7765876811740798583L;
    private static final String CANNOT_START_SESSION = "Cannot start Session";
    private static final String CANNOT_STOP_SESSION = "Cannot stop Session";
    // SESSION DATA
    private String username;
    private String password;
    private String errorMessage = "";
    private User userLogged;
    private HttpSession httpsession = null;
    private boolean loggedIn = false;
    // BEANS
    @ManagedProperty("#{navigationBean}")
    private NavigationBean navigationBean;
    @ManagedProperty("#{utilsBean}")
    private UtilsBean utilsBean;

    public String doLogin() {
        HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();

        try {
            if (username != null && password != null) {
                // validate user
                User user = this.utilsBean.getUsersService().getUserByUsername(username);
                if (user == null) {
                    userLogged = null;
                    return navigationBean.getLoginPath();
                } else {
                    userLogged = user;
                }
                request.login(username, password);

                this.httpsession = request.getSession();
                this.httpsession.setAttribute("user", username);
                this.httpsession.setAttribute("roles", user.getRoles());
                this.loggedIn = true;
                return navigationBean.getHomePath();
            }
        } catch (ServletException ex) {
            LOGGER.error(CANNOT_START_SESSION + " :", ex);
        }

        return navigationBean.getLoginPath();
    }

    public void doLogout(boolean redirect) {
        // Set the paremeter indicating that user is logged in to false
        try {
            HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
            request.logout();
            request.getSession().invalidate();
            this.loggedIn = false;
            this.httpsession = null;
            this.userLogged = null;

            if (redirect) {
                this.redirectToLogin();
            }
        } catch (ServletException | IOException ex) {
            LOGGER.error(CANNOT_STOP_SESSION + " :", ex);
        }
    }

    public String getLoginPath() {
        return "/login.jsf";
    }

    public String getHomePath() {
        return "/pages/users/management.jsf";
    }

    public void redirectToLogin() throws IOException {
        FacesContext.getCurrentInstance().getExternalContext()
                .redirect(FacesContext.getCurrentInstance().getExternalContext().getRequestContextPath() + this.getLoginPath());
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void setNavigationBean(NavigationBean navigationBean) {
        this.navigationBean = navigationBean;
    }

    public String getErrorMessage() {
        return errorMessage;
    }

    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    public boolean isLoggedIn() {
        return loggedIn;
    }

    public void setLoggedIn(boolean loggedIn) {
        this.loggedIn = loggedIn;
    }

    public User getUser() {
        return userLogged;
    }

    public UtilsBean getUtilsBean() {
        return utilsBean;
    }

    public void setUtilsBean(UtilsBean utilsBean) {
        this.utilsBean = utilsBean;
    }

    public User getUserLogged() {
        return userLogged;
    }

    public void setUserLogged(User userLogged) {
        this.userLogged = userLogged;
    }

    public String getUserRoles() {
        List<String> strRoles = new ArrayList<>();
        this.getUser().getRoles().stream().forEach(role -> strRoles.add(role.getId().toUpperCase()));
        return StringUtils.join(strRoles, ", ");
    }

    public boolean isUserInRoles(String values) {
        if (this.loggedIn) {
            List<UserRoleEnum> roles = new ArrayList<>();
            for (String value : values.split(",")) {
                roles.add(UserRoleEnum.getById(value.trim().toUpperCase()));
            }
            boolean resp = this.utilsBean.getUsersService().isUserInRoles(this.userLogged.getUsername(), roles);
            return resp;
        }
        return false;
    }
}

alex_rogget_erices/user-manager-1.0.0/user-manager-webapp-primefaces/src/main/java/cl/gechs/cursojava/beans/UtilsBean.java
package cl.gechs.cursojava.beans;

import cl.gechs.cursojava.service.UsersService;
import cl.gechs.cursojava.service.notifications.EmailNotificationService;
import cl.gechs.cursojava.service.utils.ServicesDirectory;
import java.io.Serializable;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Locale;
import java.util.TimeZone;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 *
 * @author Carlos Soza <carlos.soza at gmail.com>
 */
@ManagedBean(name = "utilsBean")
@SessionScoped
public class UtilsBean implements Serializable {

    private static final long serialVersionUID = -8176325958172860318L;

    public String getTimeZone() {
        return TimeZone.getDefault().getID();
    }

    public UsersService getUsersService() {
        return ServicesDirectory.getUserService();
    }

    public EmailNotificationService getEmailNotificationService() {
        return ServicesDirectory.getEmailNotificationService();
    }

    public Locale getLocale() {
        return new Locale.Builder().setLanguage("es").setRegion("CL").build();
    }

    public String getServerIp() throws UnknownHostException {
        return InetAddress.getLocalHost().getHostAddress();
    }

    public String getServerName() throws UnknownHostException {
        return InetAddress.getLocalHost().getHostName();
    }

}

alex_rogget_erices/user-manager-1.0.0/user-manager-webapp-primefaces/src/main/webapp/templates/footer.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <div id="footer">
        <table style="margin: 0px auto;">
            <tr>
                <td>
                    <br></br>
                    <h7 style="font-size: 70% !important;">Curso Gechs 2016.</h7>
                </td>
            </tr>
        </table>
    </div>
</ui:composition>

alex_rogget_erices/user-manager-1.0.0/user-manager-webapp-primefaces/src/main/webapp/templates/header.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://xmlns.jcp.org/jsf/core">
    <center>
        <h:form id="headerForm">
            <table border="0" style="width: 100%;">
                <tbody>
                    <tr>
                        <td rowspan="3" style="vertical-align: central">
                            <p:link outcome="#{navigationBean.homePath}">
                                <p:graphicImage name="images/gechs.png" height="36"/>
                            </p:link>
                        </td>
                        <td colspan="3" align="right" style="vertical-align: top"></td>
                    </tr>
                    <tr>
                        <td align="right" width="25%" style="font-size: 12px; vertical-align: central">
                            <span><h:outputText value="Usuario" />:</span>
                            <span><b id="header-username">#{loginBean.userLogged.username} |</b></span>
                        </td>
                        <td align="right" width="25%" style="font-size: 12px; vertical-align: central">
                            <span><h:outputText value="Perfil" />:</span>
                            <span><b id="header-perfil">#{loginBean.userRoles}</b></span>
                        </td>
                        <td>
                            <span><h:outputText value="&#160;&#160;&#160;&#160;" /></span>
                            <p:themeSwitcher effectSpeed="normal" effect="fade" style="width:165px" id="defaultSwitcher" value="#{themeSwitcherBean.theme}">
                                <f:selectItem itemLabel="Choose Theme" itemValue="" />
                                <f:selectItems value="#{themeSwitcherBean.themes}" var="theme" itemLabel="#{theme.displayName}" />
                                <p:ajax global="false" listener="#{themeSwitcherBean.saveTheme}" />
                            </p:themeSwitcher>
                        </td>

                        <td align="right" width="15%">
                            &#160;
                            <p:commandButton actionListener="#{loginBean.doLogout(true)}" icon="ui-icon-close" title="Cerrar sessión" ajax="true"/>
                        </td>
                    </tr>
                </tbody>
            </table>
        </h:form>
    </center>
</ui:composition>

alex_rogget_erices/user-manager-1.0.0/user-manager-webapp-primefaces/src/main/webapp/templates/menu.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui">
    <h:form>
        <p:outputPanel id="menuPanel">
            <p:menu id="mainMenu">
                <p:submenu label="Administración" rendered="#{loginBean.isUserInRoles('ADMINISTRADOR')}">

                    <p:menuitem value="Usuarios" icon="ui-icon-person" styleClass="#{navigationBean.getCurrentPage() eq 'users/management'?'ui-state-active':''}"
                                actionListener="#{navigationBean.setCurrentPage('users/management', true)}"
                                rendered="#{loginBean.isUserInRoles('ADMINISTRADOR')}"/>
                    <p:menuitem value="Notificaciones" icon="fa fa-paper-plane" styleClass="#{navigationBean.getCurrentPage() eq 'notifications/management'?'ui-state-active':''}"
                                actionListener="#{navigationBean.setCurrentPage('notifications/management', true)}" 
                                rendered="#{loginBean.isUserInRoles('ADMINISTRADOR')}"/>
                </p:submenu>
            </p:menu>
        </p:outputPanel>
    </h:form>
</ui:composition>

alex_rogget_erices/user-manager-1.0.0/user-manager-webapp-primefaces/src/main/webapp/templates/template.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">

    <f:view contentType="text/html" id="fview" locale="#{utilsBean.locale}">
        <f:metadata>
            <ui:insert name="metadata" />
        </f:metadata>
        <h:head>
            <title> <h:outputText value="Gechs 2016 Survey Example" /></title>
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
            <link rel="shortcut icon" type="image/x-icon" href="#{resource['images/favicon.ico']}"/>
            <script type="text/javascript">
                function handleSubmitRequest(xhr, status, args, dialogId) {
                    if (args.validationFailed) {
                        PF(dialogId).jq.effect("shake", {times: 5}, 100);
                    } else {
                        PF(dialogId).hide();
                    }
                }

                function enableTab(tabViewId, tabNumber, value, criteria) {
                    if (value == criteria) {
                        PF(tabViewId).enable(tabNumber);
                    } else {
                        PF(tabViewId).disable(tabNumber);
                    }
                }

                function enableInput(inputId, value, criteria) {
                    if (value == criteria) {
                        PF(inputId).enable();
                    } else {
                        PF(inputId).disable();
                    }
                }

                function enableInputs(inputs, value, criteria) {
                    inputs.forEach(function (entry) {
                        enableInput(entry, value, criteria);
                    });
                }

                function setStatusMessage(message) {
                    $('#txt_status_message').empty().html(message);
                }

                function startDownload() {
                    PF('statusDialog').show();
                }

                function stopDownload() {
                    PF('statusDialog').hide();
                }
            </script>

            <!-- p:calendar locale definition -->
            <script type="text/javascript">
                PrimeFaces.locales['es_CL'] = {
                    closeText: 'Cerrar',
                    prevText: 'Anterior',
                    nextText: 'Siguiente',
                    monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
                    monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
                    dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
                    dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab'],
                    dayNamesMin: ['D', 'L', 'M', 'X', 'J', 'V', 'S'],
                    weekHeader: 'Semana',
                    firstDay: 1,
                    isRTL: false,
                    showMonthAfterYear: false,
                    yearSuffix: '',
                    timeOnlyTitle: 'Sólo hora',
                    timeText: 'Tiempo',
                    hourText: 'Hora',
                    minuteText: 'Minuto',
                    secondText: 'Segundo',
                    currentText: 'Fecha actual',
                    ampm: false,
                    month: 'Mes',
                    week: 'Semana',
                    day: 'Día',
                    allDayText: 'Todo el día'
                };
            </script>
            <ui:insert name="head" />
        </h:head>

        <h:body>
            <h:outputStylesheet name="css/default.css" />

            <div id="wrapper">
                <p:dialog widgetVar="statusDialog" appendTo="@(body)" modal="true" draggable="false" closable="false" resizable="false" showHeader="false">
                    <p:panelGrid columns="1" layout="grid" style="text-align: center">
                        <p:graphicImage name="images/ajax-loader-bar.gif" />
                        <h3><span id="txt_status_message">Espere un momento por favor ...</span></h3>
                    </p:panelGrid>
                </p:dialog>

                <p:layout fullPage="true" resizeTitle="resize">
                    <p:layoutUnit position="north" resizable="false" closable="false" collapsible="false">
                        <ui:include src="header.xhtml" />
                    </p:layoutUnit>

                    <p:layoutUnit position="west" size="250" resizable="false" closable="false" collapsible="false" header="Menú Principal">
                        <ui:include src="menu.xhtml" />
                        <div style="bottom: 3px; position: absolute;">
                            Server info:<br/>
                            <ul style="margin-left: -10px"> 
                                <li><p:outputLabel value="Name: #{utilsBean.serverName}"/></li>
                                <li><p:outputLabel value="Ip:  #{utilsBean.serverIp}"/></li>
                            </ul>
                        </div>
                    </p:layoutUnit>

                    <p:layoutUnit position="center">
                        <p:growl id="main_messages" for="main_messages" showDetail="true" life="5000" autoUpdate="true" />
                        <ui:insert name="content" />
                    </p:layoutUnit>

                    <p:layoutUnit position="south" size="40">
                        <ui:include src="footer.xhtml" />
                    </p:layoutUnit>
                </p:layout>
            </div>
        </h:body>
    </f:view>
</html>		